
server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/hunansheng
      username: root
      password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    #关闭logo
    banner-mode: off

logging:
  config: classpath:log/logback.xml

mybatis-plus:
  global-config:
    #关闭logo
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
---
#开发
---
#测试
